-- Fix games table to match dev structure
ALTER TABLE games DROP COLUMN IF EXISTS week;
ALTER TABLE games ADD COLUMN week VARCHAR(10);
ALTER TABLE games ADD COLUMN IF NOT EXISTS over_odds NUMERIC(6,2);
ALTER TABLE games ADD COLUMN IF NOT EXISTS under_odds NUMERIC(6,2);
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_team_record VARCHAR(10) DEFAULT '0-0';
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_team_record VARCHAR(10) DEFAULT '0-0';